export const emojidbs=[
    {
    "phrase": "[大笑]",
    "type": "face",
    "url": require("./emoImg/emoji_0.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[大笑]",
    "picid": ""
    },
    {
    "phrase": "[可爱]",
    "type": "face",
    "url": require("./emoImg/emoji_01.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[可爱]",
    "picid": ""
    },
    {
    "phrase": "[色]",
    "type": "face",
    "url": require("./emoImg/emoji_02.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[色]",
    "picid": ""
    },
    {
    "phrase": "[嘘]",
    "type": "face",
    "url": require("./emoImg/emoji_03.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[嘘]",
    "picid": ""
    },
    {
    "phrase": "[亲]",
    "type": "face",
    "url": require("./emoImg/emoji_04.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[亲]",
    "picid": ""
    },
    {
    "phrase": "[呆]",
    "type": "face",
    "url": require("./emoImg/emoji_05.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[呆]",
    "picid": ""
    },
    {
    "phrase": "[口水]",
    "type": "face",
    "url": require("./emoImg/emoji_06.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[口水]",
    "picid": ""
    },
    {
    "phrase": "[汗]",
    "type": "face",
    "url": require("./emoImg/emoji_145.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[汗]",
    "picid": ""
    },
    {
    "phrase": "[呲牙]",
    "type": "face",
    "url": require("./emoImg/emoji_07.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[呲牙]",
    "picid": ""
    },
    {
    "phrase": "[鬼脸]",
    "type": "face",
    "url": require("./emoImg/emoji_08.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[鬼脸]",
    "picid": ""
    },
    {
    "phrase": "[害羞]",
    "type": "face",
    "url": require("./emoImg/emoji_09.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[害羞]",
    "picid": ""
    },
    {
    "phrase": "[偷笑]",
    "type": "face",
    "url": require("./emoImg/emoji_10.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[偷笑]",
    "picid": ""
    },
    {
    "phrase": "[调皮]",
    "type": "face",
    "url": require("./emoImg/emoji_11.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[调皮]",
    "picid": ""
    },
    {
    "phrase": "[可怜]",
    "type": "face",
    "url": require("./emoImg/emoji_12.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[可怜]",
    "picid": ""
    },
    {
    "phrase": "[敲]",
    "type": "face",
    "url": require("./emoImg/emoji_13.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[敲]",
    "picid": ""
    },
    {
    "phrase": "[惊讶]",
    "type": "face",
    "url": require("./emoImg/emoji_14.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[惊讶]",
    "picid": ""
    },
    {
    "phrase": "[流感]",
    "type": "face",
    "url": require("./emoImg/emoji_15.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[流感]",
    "picid": ""
    },
    {
    "phrase": "[委屈]",
    "type": "face",
    "url": require("./emoImg/emoji_16.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[委屈]",
    "picid": ""
    },
    {
    "phrase": "[流泪]",
    "type": "face",
    "url": require("./emoImg/emoji_17.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[流泪]",
    "picid": ""
    },
    {
    "phrase": "[嚎哭]",
    "type": "face",
    "url": require("./emoImg/emoji_18.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[嚎哭]",
    "picid": ""
    },
    {
    "phrase": "[惊恐]",
    "type": "face",
    "url": require("./emoImg/emoji_19.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[惊恐]",
    "picid": ""
    },
    {
    "phrase": "[怒]",
    "type": "face",
    "url": require("./emoImg/emoji_20.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[怒]",
    "picid": ""
    },
    {
    "phrase": "[酷]",
    "type": "face",
    "url": require("./emoImg/emoji_21.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[酷]",
    "picid": ""
    },
    {
    "phrase": "[不说]",
    "type": "face",
    "url": require("./emoImg/emoji_22.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[不说]",
    "picid": ""
    },
    {
    "phrase": "[鄙视]",
    "type": "face",
    "url": require("./emoImg/emoji_23.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[鄙视]",
    "picid": ""
    },
    {
    "phrase": "[阿弥陀佛]",
    "type": "face",
    "url": require("./emoImg/emoji_24.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[阿弥陀佛]",
    "picid": ""
    },
    {
    "phrase": "[奸笑]",
    "type": "face",
    "url": require("./emoImg/emoji_25.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[奸笑]",
    "picid": ""
    },
    {
    "phrase": "[睡着]",
    "type": "face",
    "url": require("./emoImg/emoji_26.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[睡着]",
    "picid": ""
    },
    {
    "phrase": "[口罩]",
    "type": "face",
    "url": require("./emoImg/emoji_27.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[口罩]",
    "picid": ""
    },
    {
    "phrase": "[努力]",
    "type": "face",
    "url": require("./emoImg/emoji_28.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[努力]",
    "picid": ""
    },
    {
    "phrase": "[抠鼻孔]",
    "type": "face",
    "url": require("./emoImg/emoji_29.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[抠鼻孔]",
    "picid": ""
    },
    {
    "phrase": "[疑问]",
    "type": "face",
    "url": require("./emoImg/emoji_30.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[疑问]",
    "picid": ""
    },
    {
    "phrase": "[怒骂]",
    "type": "face",
    "url": require("./emoImg/emoji_31.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[怒骂]",
    "picid": ""
    },
    {
    "phrase": "[晕]",
    "type": "face",
    "url": require("./emoImg/emoji_32.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[晕]",
    "picid": ""
    },
    {
    "phrase": "[呕吐]",
    "type": "face",
    "url": require("./emoImg/emoji_33.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[呕吐]",
    "picid": ""
    },
    {
    "phrase": "[拜一拜]",
    "type": "face",
    "url": require("./emoImg/emoji_160.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[拜一拜]",
    "picid": ""
    },
    {
    "phrase": "[惊喜]",
    "type": "face",
    "url": require("./emoImg/emoji_161.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[惊喜]",
    "picid": ""
    },
    {
    "phrase": "[流汗]",
    "type": "face",
    "url": require("./emoImg/emoji_162.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[流汗]",
    "picid": ""
    },
    {
    "phrase": "[卖萌]",
    "type": "face",
    "url": require("./emoImg/emoji_163.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[卖萌]",
    "picid": ""
    },
    {
    "phrase": "[默契眨眼]",
    "type": "face",
    "url": require("./emoImg/emoji_164.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[默契眨眼]",
    "picid": ""
    },
    {
    "phrase": "[烧香拜佛]",
    "type": "face",
    "url": require("./emoImg/emoji_165.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[烧香拜佛]",
    "picid": ""
    },
    {
    "phrase": "[晚安]",
    "type": "face",
    "url": require("./emoImg/emoji_166.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[晚安]",
    "picid": ""
    },
    {
    "phrase": "[强]",
    "type": "face",
    "url": require("./emoImg/emoji_34.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[强]",
    "picid": ""
    },
    {
    "phrase": "[弱]",
    "type": "face",
    "url": require("./emoImg/emoji_35.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[弱]",
    "picid": ""
    },
    {
    "phrase": "[OK]",
    "type": "face",
    "url": require("./emoImg/emoji_36.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[OK]",
    "picid": ""
    },
    {
    "phrase": "[拳头]",
    "type": "face",
    "url": require("./emoImg/emoji_37.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[拳头]",
    "picid": ""
    },
    {
    "phrase": "[胜利]",
    "type": "face",
    "url": require("./emoImg/emoji_38.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[胜利]",
    "picid": ""
    },
    {
    "phrase": "[鼓掌]",
    "type": "face",
    "url": require("./emoImg/emoji_39.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[鼓掌]",
    "picid": ""
    },
    {
    "phrase": "[握手]",
    "type": "face",
    "url": require("./emoImg/emoji_200.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[握手]",
    "picid": ""
    },
    {
    "phrase": "[发怒]",
    "type": "face",
    "url": require("./emoImg/emoji_40.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[发怒]",
    "picid": ""
    },
    {
    "phrase": "[骷髅]",
    "type": "face",
    "url": require("./emoImg/emoji_41.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[骷髅]",
    "picid": ""
    },
    {
    "phrase": "[便便]",
    "type": "face",
    "url": require("./emoImg/emoji_42.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[便便]",
    "picid": ""
    },
    {
    "phrase": "[火]",
    "type": "face",
    "url": require("./emoImg/emoji_43.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[火]",
    "picid": ""
    },
    {
    "phrase": "[溜]",
    "type": "face",
    "url": require("./emoImg/emoji_44.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[溜]",
    "picid": ""
    },
    {
    "phrase": "[爱心]",
    "type": "face",
    "url": require("./emoImg/emoji_45.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[爱心]",
    "picid": ""
    },
    {
    "phrase": "[心碎]",
    "type": "face",
    "url": require("./emoImg/emoji_46.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[心碎]",
    "picid": ""
    },
    {
    "phrase": "[钟情]",
    "type": "face",
    "url": require("./emoImg/emoji_47.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[钟情]",
    "picid": ""
    },
    {
    "phrase": "[唇]",
    "type": "face",
    "url": require("./emoImg/emoji_48.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[唇]",
    "picid": ""
    },
    {
    "phrase": "[戒指]",
    "type": "face",
    "url": require("./emoImg/emoji_49.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[戒指]",
    "picid": ""
    },
    {
    "phrase": "[钻石]",
    "type": "face",
    "url": require("./emoImg/emoji_50.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[钻石]",
    "picid": ""
    },
    {
    "phrase": "[太阳]",
    "type": "face",
    "url": require("./emoImg/emoji_51.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[太阳]",
    "picid": ""
    },
    {
    "phrase": "[有时晴]",
    "type": "face",
    "url": require("./emoImg/emoji_52.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[有时晴]",
    "picid": ""
    },
    {
    "phrase": "[多云]",
    "type": "face",
    "url": require("./emoImg/emoji_53.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[多云]",
    "picid": ""
    },
    {
    "phrase": "[雷]",
    "type": "face",
    "url": require("./emoImg/emoji_54.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[雷]",
    "picid": ""
    },
    {
    "phrase": "[雨]",
    "type": "face",
    "url": require("./emoImg/emoji_55.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[雨]",
    "picid": ""
    },
    {
    "phrase": "[雪花]",
    "type": "face",
    "url": require("./emoImg/emoji_56.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[雪花]",
    "picid": ""
    },
    {
    "phrase": "[爱人]",
    "type": "face",
    "url": require("./emoImg/emoji_57.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[爱人]",
    "picid": ""
    },
    {
    "phrase": "[帽子]",
    "type": "face",
    "url": require("./emoImg/emoji_58.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[帽子]",
    "picid": ""
    },
    {
    "phrase": "[皇冠]",
    "type": "face",
    "url": require("./emoImg/emoji_59.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[皇冠]",
    "picid": ""
    },
    {
    "phrase": "[篮球]",
    "type": "face",
    "url": require("./emoImg/emoji_60.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[篮球]",
    "picid": ""
    },
    {
    "phrase": "[足球]",
    "type": "face",
    "url": require("./emoImg/emoji_61.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[足球]",
    "picid": ""
    },
    {
    "phrase": "[垒球]",
    "type": "face",
    "url": require("./emoImg/emoji_62.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[垒球]",
    "picid": ""
    },
    {
    "phrase": "[网球]",
    "type": "face",
    "url": require("./emoImg/emoji_63.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[网球]",
    "picid": ""
    },
    {
    "phrase": "[台球]",
    "type": "face",
    "url": require("./emoImg/emoji_64.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[台球]",
    "picid": ""
    },
    {
    "phrase": "[咖啡]",
    "type": "face",
    "url": require("./emoImg/emoji_65.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[咖啡]",
    "picid": ""
    },
    {
    "phrase": "[啤酒]",
    "type": "face",
    "url": require("./emoImg/emoji_66.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[啤酒]",
    "picid": ""
    },
    {
    "phrase": "[干杯]",
    "type": "face",
    "url": require("./emoImg/emoji_67.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[干杯]",
    "picid": ""
    },
    {
    "phrase": "[柠檬汁]",
    "type": "face",
    "url": require("./emoImg/emoji_68.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[柠檬汁]",
    "picid": ""
    },
    {
    "phrase": "[餐具]",
    "type": "face",
    "url": require("./emoImg/emoji_69.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[餐具]",
    "picid": ""
    },
    {
    "phrase": "[汉堡]",
    "type": "face",
    "url": require("./emoImg/emoji_70.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[汉堡]",
    "picid": ""
    },
    {
    "phrase": "[鸡腿]",
    "type": "face",
    "url": require("./emoImg/emoji_71.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[鸡腿]",
    "picid": ""
    },
    {
    "phrase": "[面条]",
    "type": "face",
    "url": require("./emoImg/emoji_72.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[面条]",
    "picid": ""
    },
    {
    "phrase": "[冰淇淋]",
    "type": "face",
    "url": require("./emoImg/emoji_73.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[冰淇淋]",
    "picid": ""
    },
    {
    "phrase": "[沙冰]",
    "type": "face",
    "url": require("./emoImg/emoji_74.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[沙冰]",
    "picid": ""
    },
    {
    "phrase": "[生日蛋糕]",
    "type": "face",
    "url": require("./emoImg/emoji_75.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[生日蛋糕]",
    "picid": ""
    },
    {
    "phrase": "[蛋糕]",
    "type": "face",
    "url": require("./emoImg/emoji_76.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[蛋糕]",
    "picid": ""
    },
    {
    "phrase": "[糖果]",
    "type": "face",
    "url": require("./emoImg/emoji_77.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[糖果]",
    "picid": ""
    },
    {
    "phrase": "[葡萄]",
    "type": "face",
    "url": require("./emoImg/emoji_78.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[葡萄]",
    "picid": ""
    },
    {
    "phrase": "[西瓜]",
    "type": "face",
    "url": require("./emoImg/emoji_79.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[西瓜]",
    "picid": ""
    },
    {
    "phrase": "[光碟]",
    "type": "face",
    "url": require("./emoImg/emoji_80.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[光碟]",
    "picid": ""
    },
    {
    "phrase": "[手机]",
    "type": "face",
    "url": require("./emoImg/emoji_81.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[手机]",
    "picid": ""
    },
    {
    "phrase": "[电话]",
    "type": "face",
    "url": require("./emoImg/emoji_82.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[电话]",
    "picid": ""
    },
    {
    "phrase": "[电视]",
    "type": "face",
    "url": require("./emoImg/emoji_83.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[电视]",
    "picid": ""
    },
    {
    "phrase": "[声音开启]",
    "type": "face",
    "url": require("./emoImg/emoji_84.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[声音开启]",
    "picid": ""
    },
    {
    "phrase": "[声音关闭]",
    "type": "face",
    "url": require("./emoImg/emoji_85.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[声音关闭]",
    "picid": ""
    },
    {
    "phrase": "[铃铛]",
    "type": "face",
    "url": require("./emoImg/emoji_86.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[铃铛]",
    "picid": ""
    },
    {
    "phrase": "[锁头]",
    "type": "face",
    "url": require("./emoImg/emoji_87.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[锁头]",
    "picid": ""
    },
    {
    "phrase": "[放大镜]",
    "type": "face",
    "url": require("./emoImg/emoji_88.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[放大镜]",
    "picid": ""
    },
    {
    "phrase": "[灯泡]",
    "type": "face",
    "url": require("./emoImg/emoji_89.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[灯泡]",
    "picid": ""
    },
    {
    "phrase": "[锤头]",
    "type": "face",
    "url": require("./emoImg/emoji_90.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[锤头]",
    "picid": ""
    },
    {
    "phrase": "[烟]",
    "type": "face",
    "url": require("./emoImg/emoji_91.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[烟]",
    "picid": ""
    },
    {
    "phrase": "[炸弹]",
    "type": "face",
    "url": require("./emoImg/emoji_92.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[炸弹]",
    "picid": ""
    },
    {
    "phrase": "[枪]",
    "type": "face",
    "url": require("./emoImg/emoji_93.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[枪]",
    "picid": ""
    },
    {
    "phrase": "[刀]",
    "type": "face",
    "url": require("./emoImg/emoji_94.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[刀]",
    "picid": ""
    },
    {
    "phrase": "[药]",
    "type": "face",
    "url": require("./emoImg/emoji_95.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[药]",
    "picid": ""
    },
    {
    "phrase": "[打针]",
    "type": "face",
    "url": require("./emoImg/emoji_96.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[打针]",
    "picid": ""
    },
    {
    "phrase": "[钱袋]",
    "type": "face",
    "url": require("./emoImg/emoji_97.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[钱袋]",
    "picid": ""
    },
    {
    "phrase": "[钞票]",
    "type": "face",
    "url": require("./emoImg/emoji_98.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[钞票]",
    "picid": ""
    },
    {
    "phrase": "[银行卡]",
    "type": "face",
    "url": require("./emoImg/emoji_99.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[银行卡]",
    "picid": ""
    },
    {
    "phrase": "[手柄]",
    "type": "face",
    "url": require("./emoImg/emoji_100.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[手柄]",
    "picid": ""
    },
    {
    "phrase": "[麻将]",
    "type": "face",
    "url": require("./emoImg/emoji_101.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[麻将]",
    "picid": ""
    },
    {
    "phrase": "[调色板]",
    "type": "face",
    "url": require("./emoImg/emoji_102.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[调色板]",
    "picid": ""
    },
    {
    "phrase": "[电影]",
    "type": "face",
    "url": require("./emoImg/emoji_103.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[电影]",
    "picid": ""
    },
    {
    "phrase": "[麦克风]",
    "type": "face",
    "url": require("./emoImg/emoji_104.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[麦克风]",
    "picid": ""
    },
    {
    "phrase": "[耳机]",
    "type": "face",
    "url": require("./emoImg/emoji_105.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[耳机]",
    "picid": ""
    },
    {
    "phrase": "[音乐]",
    "type": "face",
    "url": require("./emoImg/emoji_106.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[音乐]",
    "picid": ""
    },
    {
    "phrase": "[吉他]",
    "type": "face",
    "url": require("./emoImg/emoji_107.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[吉他]",
    "picid": ""
    },
    {
    "phrase": "[火箭]",
    "type": "face",
    "url": require("./emoImg/emoji_108.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[火箭]",
    "picid": ""
    },
    {
    "phrase": "[飞机]",
    "type": "face",
    "url": require("./emoImg/emoji_109.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[飞机]",
    "picid": ""
    },
    {
    "phrase": "[火车]",
    "type": "face",
    "url": require("./emoImg/emoji_110.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[火车]",
    "picid": ""
    },
    {
    "phrase": "[公交]",
    "type": "face",
    "url": require("./emoImg/emoji_111.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[公交]",
    "picid": ""
    },
    {
    "phrase": "[轿车]",
    "type": "face",
    "url": require("./emoImg/emoji_112.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[轿车]",
    "picid": ""
    },
    {
    "phrase": "[出租车]",
    "type": "face",
    "url": require("./emoImg/emoji_113.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[出租车]",
    "picid": ""
    },
    {
    "phrase": "[警车]",
    "type": "face",
    "url": require("./emoImg/emoji_114.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[警车]",
    "picid": ""
    },
    {
    "phrase": "[自行车]",
    "type": "face",
    "url": require("./emoImg/emoji_115.png"),
    "hot": false,
    "common": true,
    "category": "",
    "icon": " ",
    "value": "[自行车]",
    "picid": ""
    }
    ]